version: 2.1
orbs:
  node: circleci/node@3.0.0

commands:
  build:
    description: |
      Create a production build
    steps:
      - run:
          command: mkdir -p /tmp/artifacts
          name: Ensure artifacts directory is present
      - run: NODE_ENV=production npm run build
      - run: cp -r ./build /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

  install:
    description: |
      Install dependencies
    steps:
      - run: npm install

  test:
    description: |
      Run tests using Jest
    steps:
      - run:
          command: npm run test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/js-test-results.xml
          name: Run tests with JUnit as reporter

jobs:
  build-job:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - m2-{{ checksum "package-lock.json" }}
      - install
      - test
      - build
      - save_cache:
          key: m2-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

workflows:
  build:
    jobs:
      - build-job

