version: 2.1
orbs:
  node: circleci/node@3.0.0
  aws-s3: circleci/aws-s3@2.0.0

commands:
  build:
    description: |
      Create a production build
    steps:
      - run:
          command: mkdir -p /tmp/artifacts
          name: Ensure artifacts directory is present
      - run: NODE_ENV=production npm run build
      - run: cp -r ./build /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts

  install:
    description: |
      Install dependencies
    steps:
      - run: npm ci

  test:
    description: |
      Run tests using Jest
    steps:
      - run:
          command: npm run test:ci
          name: Run tests with JUnit as reporter
      - run:
          command: ls -l
      - store_test_results:
          path: junit.xml

  sync-to-s3:
    description: |
      Sync files to s3 bucket
    steps:
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: build
          to: 's3://react-deploy-pipeline'

jobs:
  build-job:
    docker:
      - image: circleci/node:14-browsers
    resource_class: small
    steps:
      - checkout
      - install
      - test
      - build
      - sync-to-s3

workflows:
  build:
    jobs:
      - build-job:
          context: S3 Creds

